// Central API client — all fetch calls go through here.
// Key behaviors:
//   • Idempotency: caller supplies a stable UUID for POST; we never generate one here.
//   • Retry: POST is retried up to MAX_RETRIES times on network failures / 5xx responses.
//   • AbortController: callers can cancel in-flight requests.

const BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:3001";
const MAX_RETRIES = 3;
const RETRY_DELAY_MS = 800;

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function apiFetch(path, options = {}, retries = 0) {
  const url = `${BASE_URL}${path}`;
  try {
    const res = await fetch(url, {
      headers: { "Content-Type": "application/json", ...options.headers },
      ...options,
    });

    // 4xx — don't retry, surface the error body
    if (res.status >= 400 && res.status < 500) {
      const body = await res.json().catch(() => ({}));
      throw new ApiError(res.status, body.errors || body.error || "Request failed");
    }

    // 5xx — retry with back-off
    if (res.status >= 500) {
      if (retries < MAX_RETRIES) {
        await sleep(RETRY_DELAY_MS * 2 ** retries);
        return apiFetch(path, options, retries + 1);
      }
      throw new ApiError(res.status, "Server error — please try again later");
    }

    if (res.status === 204) return null;
    return res.json();
  } catch (err) {
    if (err instanceof ApiError) throw err;
    // Network error — retry
    if (retries < MAX_RETRIES) {
      await sleep(RETRY_DELAY_MS * 2 ** retries);
      return apiFetch(path, options, retries + 1);
    }
    throw new ApiError(0, "Network error — check your connection");
  }
}

export class ApiError extends Error {
  constructor(status, message) {
    super(typeof message === "string" ? message : JSON.stringify(message));
    this.status = status;
    this.details = message;
  }
}

// ── Expenses ──────────────────────────────────────────────────────────────────

/**
 * Create an expense. `id` must be a stable UUID generated by the caller
 * so retries are idempotent.
 */
export async function createExpense(payload, signal) {
  return apiFetch("/expenses", {
    method: "POST",
    body: JSON.stringify(payload),
    signal,
  });
}

/**
 * @param {Object} params
 * @param {string} [params.category]
 * @param {'date_desc'} [params.sort]
 */
export async function fetchExpenses({ category, sort } = {}, signal) {
  const qs = new URLSearchParams();
  if (category) qs.set("category", category);
  if (sort) qs.set("sort", sort);
  const query = qs.toString() ? `?${qs}` : "";
  return apiFetch(`/expenses${query}`, { signal });
}

export async function deleteExpense(id, signal) {
  return apiFetch(`/expenses/${id}`, { method: "DELETE", signal });
}

export async function fetchCategories(signal) {
  return apiFetch("/expenses/categories", { signal });
}